CSA-36
bootcamp2024-quantum/core-frontend pull request #2
Opened 2024-03-18 17:02 UTC by VovaLyapota

- add env-file to docker-compose.yml
- update readme.md
- add .env to .gitignore

2024-03-18 21:10 UTC, ssliadniev requested changes

2024-03-19 11:26 UTC, StanislavKharkiv commented on .env.example
> +URL="http://localhost:7777"
please make two variables URL and PORT and use PORT in docker-compose
[exemple](https://stackoverflow.com/questions/29377853/how-can-i-use-environment-variables-in-docker-compose)

2024-03-19 13:58 UTC, StanislavKharkiv approved these changes

2024-03-19 13:59 UTC, ssliadniev approved these changes

2024-03-19 14:00 UTC, merged